gfxexport Tu_bg.swf -d Tu_bg
gfxexport Tu_capsule_kit_open.swf -d Tu_capsule_kit_open
gfxexport Tu_Character_Info.swf -d Tu_Character_Info
gfxexport Tu_Chatting.swf -d Tu_Chatting
gfxexport Tu_Icon_Select.swf -d Tu_Icon_Select
gfxexport Tu_Item_pickup.swf -d Tu_Item_pickup
gfxexport Tu_Keyboard_Ctrl.swf -d Tu_Keyboard_Ctrl
gfxexport Tu_Keyboard_F1.swf -d Tu_Keyboard_F1
gfxexport Tu_Keyboard_T.swf -d Tu_Keyboard_T
gfxexport Tu_Main_menu.swf -d Tu_Main_menu
gfxexport Tu_MainMenu_button.swf -d Tu_MainMenu_button
gfxexport Tu_Mini_Map.swf -d Tu_Mini_Map
gfxexport Tu_Mob_attack.swf -d Tu_Mob_attack
gfxexport Tu_Mob_select.swf -d Tu_Mob_select
gfxexport Tu_Mouse_L_click.swf -d Tu_Mouse_L_click
gfxexport Tu_Mouse_R_move.swf -d Tu_Mouse_R_move
gfxexport Tu_OK.swf -d Tu_OK
gfxexport Tu_pc_state.swf -d Tu_pc_state
gfxexport Tu_scouter_icon_install.swf -d Tu_scouter_icon_install
gfxexport Tu_scouter_icon_move.swf -d Tu_scouter_icon_move
gfxexport Tu_W.A.S.D.swf -d Tu_W.A.S.D
gfxexport Tu_X_Button.swf -d Tu_X_Button
gfxexport Tu_Skill_Info.swf -d Tu_Skill_Info